"""add generated_url field to link table

Revision ID: 04d5f0051996
Revises: 3549dffc6965
Create Date: 2025-01-07 00:24:17.703630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d5f0051996'
down_revision: Union[str, None] = '3549dffc6965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('generated_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'generated_url')
    # ### end Alembic commands ###
