"""add generated_url field to link_interaction table

Revision ID: 31119622b9d6
Revises: 04d5f0051996
Create Date: 2025-01-07 00:27:22.934056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31119622b9d6'
down_revision: Union[str, None] = '04d5f0051996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('link_interaction', sa.Column('generated_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_link_interaction_generated_url'), 'link_interaction', ['generated_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_interaction_generated_url'), table_name='link_interaction')
    op.drop_column('link_interaction', 'generated_url')
    op.alter_column('link', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
