"""add rename field on link table

Revision ID: 3549dffc6965
Revises: ba826fd381df
Create Date: 2025-01-06 23:25:10.951384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3549dffc6965'
down_revision: Union[str, None] = 'ba826fd381df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_column('link', 'expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('link', 'expires_at')
    # ### end Alembic commands ###
