"""add status to link table

Revision ID: 3db2d6be2e87
Revises: 6e0da1708cbd
Create Date: 2025-01-11 23:18:33.377833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db2d6be2e87'
down_revision: Union[str, None] = '6e0da1708cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('link', 'favicon_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'favicon_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('link', 'status')
    # ### end Alembic commands ###
