"""create link interaction table

Revision ID: 61bca61b589d
Revises: efaedb25e2fa
Create Date: 2024-12-30 23:49:24.186043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bca61b589d'
down_revision: Union[str, None] = 'efaedb25e2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('campaign', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index(op.f('ix_link_interaction_browser'), 'link_interaction', ['browser'], unique=False)
    op.create_index(op.f('ix_link_interaction_campaign'), 'link_interaction', ['campaign'], unique=False)
    op.create_index(op.f('ix_link_interaction_city'), 'link_interaction', ['city'], unique=False)
    op.create_index(op.f('ix_link_interaction_continent'), 'link_interaction', ['continent'], unique=False)
    op.create_index(op.f('ix_link_interaction_country'), 'link_interaction', ['country'], unique=False)
    op.create_index(op.f('ix_link_interaction_created_at'), 'link_interaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_link_interaction_device'), 'link_interaction', ['device'], unique=False)
    op.create_index(op.f('ix_link_interaction_domain'), 'link_interaction', ['domain'], unique=False)
    op.create_index(op.f('ix_link_interaction_link_id'), 'link_interaction', ['link_id'], unique=False)
    op.create_index(op.f('ix_link_interaction_medium'), 'link_interaction', ['medium'], unique=False)
    op.create_index(op.f('ix_link_interaction_operating_system'), 'link_interaction', ['operating_system'], unique=False)
    op.create_index(op.f('ix_link_interaction_original_url'), 'link_interaction', ['original_url'], unique=False)
    op.create_index(op.f('ix_link_interaction_path'), 'link_interaction', ['path'], unique=False)
    op.create_index(op.f('ix_link_interaction_region'), 'link_interaction', ['region'], unique=False)
    op.create_index(op.f('ix_link_interaction_shortcode'), 'link_interaction', ['shortcode'], unique=False)
    op.create_index(op.f('ix_link_interaction_source'), 'link_interaction', ['source'], unique=False)
    op.create_index(op.f('ix_link_interaction_user_id'), 'link_interaction', ['user_id'], unique=False)

    op.execute("SELECT create_hypertable('link_interaction', by_range('created_at'));")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SELECT drop_hypertable('link_interaction');")
    op.drop_index(op.f('ix_link_interaction_user_id'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_source'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_shortcode'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_region'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_path'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_original_url'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_operating_system'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_medium'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_link_id'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_domain'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_device'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_created_at'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_country'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_continent'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_city'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_campaign'), table_name='link_interaction')
    op.drop_index(op.f('ix_link_interaction_browser'), table_name='link_interaction')
    op.drop_table('link_interaction')
    # ### end Alembic commands ###
