"""add password to link table

Revision ID: 6c0439313838
Revises: ca82f3b3fd8b
Create Date: 2025-02-15 18:35:37.110557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0439313838'
down_revision: Union[str, None] = 'ca82f3b3fd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'password')
    # ### end Alembic commands ###
