"""add favicon url to link table

Revision ID: 6e0da1708cbd
Revises: 31a2f63504c7
Create Date: 2025-01-11 21:12:59.807591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0da1708cbd'
down_revision: Union[str, None] = '31a2f63504c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('favicon_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'favicon_url')
    # ### end Alembic commands ###
