"""remove qrcode from link table

Revision ID: 757db8ffb2d8
Revises: 61bca61b589d
Create Date: 2025-01-06 22:33:26.110651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757db8ffb2d8'
down_revision: Union[str, None] = '61bca61b589d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'qrcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('qrcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
