"""remove path from refere table

Revision ID: a0a3a775adde
Revises: 31119622b9d6
Create Date: 2025-01-07 14:13:43.054518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a3a775adde'
down_revision: Union[str, None] = '31119622b9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link_interaction', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_link_interaction_path', table_name='link_interaction')
    op.drop_column('link_interaction', 'path')
    op.drop_column('referer', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referer', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('link_interaction', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_link_interaction_path', 'link_interaction', ['path'], unique=False)
    op.alter_column('link_interaction', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
