"""qrcode to link table

Revision ID: efaedb25e2fa
Revises: eb92dd5d9a51
Create Date: 2024-12-20 23:42:29.344653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaedb25e2fa'
down_revision: Union[str, None] = 'eb92dd5d9a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('qrcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'qrcode')
    # ### end Alembic commands ###
