"""add utm table

Revision ID: f661277fe815
Revises: 1331af4fa356
Create Date: 2024-12-20 12:42:03.277457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f661277fe815'
down_revision: Union[str, None] = '1331af4fa356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utm',
    sa.Column('campaign', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign', 'source', 'user_id')
    )
    op.add_column('link', sa.Column('utm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'utm', ['utm_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'utm_id')
    op.drop_table('utm')
    # ### end Alembic commands ###
