default_language_version:
  python: python3.11.5
  node: "22.11.0"

repos:
  # ESLint for JavaScript/TypeScript in the `ui` directory
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        name: eslint (ui)
        verbose: true
        args:
          - --color
          - --fix
        # Only run eslint in the `ui` folder
        files: ^ui/

  # General hooks for code hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: /README\.rst$|\.pot?$|^ui/
      - id: end-of-file-fixer
        exclude: /README\.rst$|\.pot?$|^ui/
      - id: debug-statements
        exclude: ^ui/
      - id: fix-encoding-pragma
        args: ["--remove"]
        exclude: ^ui/
      - id: check-case-conflict
      - id: check-docstring-first
        exclude: ^ui/
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        exclude: /README\.rst$|^docs/.*\.rst$|^ui/
      - id: check-symlinks
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^ui/

  # Ruff for Python in the `api` directory
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^api/
      - id: ruff-format
        files: ^api/
