services:
  backend:
    build: ./api
    container_name: backend
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - timescaledb
      - redis

  frontend:
    build: ./ui
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./ui/.env

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  timescaledb-data:
