version: 1
disable_existing_loggers: false
formatters:
  access:
    "()": "core.logs.CustomFormatter"
    fmt: "%(asctime)s : %(levelprefix)s %(client_addr)s - \"%(request_line)s\" %(status_code)s Process Time: %(process_time).2f sec"
    use_colors: true
  default:
    "()": "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s : %(levelprefix)s %(message)s"
    use_colors: true
  file:
    format: "%(asctime)s : %(levelname)s : %(message)s Process Time: %(process_time).2f sec"
handlers:
  access:
    class: "logging.StreamHandler"
    formatter: "access"
    stream: "ext://sys.stdout"
  default:
    class: "logging.StreamHandler"
    formatter: "default"
    stream: "ext://sys.stderr"
  file:
    class: "logging.FileHandler"
    formatter: "file"
    filename: "api-server.log"
    mode: "a"
loggers:
  uvicorn:
    handlers:
      - "default"
      - "file"
    level: "INFO"
    propagate: false
  uvicorn.access:
    handlers:
      - "access"
      - "file"
    level: "INFO"
    propagate: false
  uvicorn.error:
    handlers:
      - "default"
      - "file"
    level: "INFO"
    propagate: false
